### ISSUE TITLE
fp16 mixed precision requires a GPU

### ISSUE THREAD

**Issue by thistleknot** [Xylambda/attention#1] opened 2022-08-14 15:23 UTC
I'm running this with python 3.9.9 so that might be the issue.  I also ignored the requirements file (I just installed the needed torch libraries).

However. I do have a gpu and have ran cuda enabled libraries.

So I'm unsure how to resolve

"fp16 mixed precision requires a GPU"

**Comment by Xylambda** [comment] 2022-08-14 17:14
Hi,

thanks for opening the issue. I would need more information to provide a solution.

Could you please provide a short MRE? What commands are you running, how you set up your env., etc.

I would also like to know your environment configuration. With the environment active, you could simply run `pip freeze` in the command line and paste the output here.

Without having the whole picture, my first guess is that either CUDA libraries are not well setup or that there is an issue with the library that is used to train the models, which is [torchfitter](https://github.com/Xylambda/torchfitter).

To test the first guess, you may write the following in python:

```python
import torch
print(torch.cuda.is_available())
```

If it says False, there is an issue with the way you have installed the CUDA binaries.

To test the second guess, you may set the variable `mixed_precision` to False in the Trainer ([this line](https://github.com/Xylambda/attention/blob/main/utils.py#L153)) and check if everything works.

**Comment by thistleknot** [comment] 2022-08-14 19:11
pip freeze
```
absl-py==1.2.0
accelerate==0.12.0
aiohttp==3.8.1
aiosignal==1.2.0
anyio==3.6.1
appnope==0.1.3
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
asttokens==2.0.5
astunparse==1.6.3
async-timeout==4.0.2
atomicwrites==1.4.1
atoti==0.6.6
atoti-core==0.6.6
atoti-query==0.6.6
attrs==22.1.0
AutoTS==0.4.2
Babel==2.10.3
backcall==0.2.0
beautifulsoup4==4.11.1
bleach==5.0.1
blis==0.7.8
blosc==1.10.6
boto3==1.24.42
botocore==1.27.42
bravado==11.0.3
bravado-core==5.17.0
CacheControl==0.12.11
cachetools==5.2.0
cachy==0.3.0
catalogue==2.0.8
certifi==2022.6.15
cffi==1.15.1
charset-normalizer==2.1.0
clang==5.0
cleo==0.8.1
click==8.1.3
clikit==0.6.2
cloudpickle==2.0.0
clustergram==0.6.0
cmdstanpy==1.0.4
colorama==0.4.5
commonmark==0.9.1
convertdate==2.4.0
crashtest==0.3.1
cycler==0.11.0
cymem==2.0.6
Cython==0.29.32
dask==2021.11.2
dataframe-image==0.1.1
DateTime==4.5
debugpy==1.6.2
decorator==5.1.1
defusedxml==0.7.1
Deprecated==1.2.13
deprecation==2.1.0
distlib==0.3.5
distributed==2021.11.2
docutils==0.19
entrypoints==0.4
ephem==4.1.3
et-xmlfile==1.1.0
exchange-calendars==4.1.1
executing==0.9.1
fastjsonschema==2.16.1
filelock==3.7.1
flatbuffers==1.12
fonttools==4.34.4
frozenlist==1.3.0
fsspec==2022.7.1
future==0.18.2
gast==0.4.0
gitdb==4.0.9
GitPython==3.1.27
google-auth==2.9.1
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
grpcio==1.48.0
h5py==3.1.0
HeapDict==1.0.1
hijri-converter==2.2.4
holidays==0.14.2
html5lib==1.1
idna==3.3
img2pdf==0.4.4
importlib==1.0.4
importlib-metadata==4.12.0
iniconfig==1.1.1
ipykernel==6.15.1
ipynbname==2021.3.2
ipython==8.4.0
ipython-genutils==0.2.0
ipywidgets==7.7.1
jdk4py==17.0.3.0
jedi==0.18.1
Jinja2==3.1.2
jmespath==1.0.1
joblib==1.1.0
json5==0.9.8
jsonpointer==2.3
jsonref==0.2
jsonschema==3.2.0
jupyter-client==7.3.4
jupyter-core==4.11.1
jupyter-server==1.18.1
jupyterlab==3.4.4
jupyterlab-pygments==0.2.2
jupyterlab-server==2.15.0
jupyterlab-widgets==1.1.1
k-means-constrained==0.7.1
keras==2.8.0
keras-models==0.0.7
Keras-Preprocessing==1.1.2
keyring==23.7.0
kiwisolver==1.4.4
korean-lunar-calendar==0.2.1
langcodes==3.3.0
libclang==14.0.1
locket==1.0.0
lockfile==0.12.2
LunarCalendar==0.0.9
lxml==4.9.1
lz4==4.0.2
Markdown==3.4.1
MarkupSafe==2.1.1
matplotlib==3.5.2
matplotlib-inline==0.1.3
mistune==0.8.4
monotonic==1.6
more-itertools==8.13.0
msgpack==1.0.3
multidict==6.0.2
multitasking==0.0.11
murmurhash==1.0.7
nbclassic==0.4.3
nbclient==0.6.6
nbconvert==6.5.0
nbformat==5.4.0
neptune-client==0.16.4
nest-asyncio==1.5.5
notebook==6.4.12
notebook-shim==0.1.0
numpy==1.23.1
oauthlib==3.2.0
opencv-python==4.6.0.66
openpyxl==3.0.10
opt-einsum==3.3.0
ortools==9.3.10497
packaging==20.9
pandas==1.2.5
pandas-datareader==0.10.0
pandas-market-calendars==3.5
pandocfilters==1.5.0
parso==0.8.3
partd==1.2.0
pastel==0.2.1
pathlib==1.0.1
pathy==0.6.2
patsy==0.5.2
pexpect==4.8.0
pickleshare==0.7.5
pikepdf==5.4.2
Pillow==9.2.0
pipenv==2022.7.24
pivottablejs==0.9.0
pkginfo==1.8.3
platformdirs==2.5.2
plotly==5.9.0
pluggy==1.0.0
pmdarima==1.8.5
poetry==1.1.14
poetry-core==1.0.8
preshed==3.0.6
prometheus-client==0.14.1
prompt-toolkit==3.0.30
prophet==1.1
protobuf==3.19.4
psutil==5.9.1
ptyprocess==0.7.0
pure-eval==0.2.2
py==1.11.0
py4j==0.10.9.5
pyarrow==6.0.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
pydantic==1.9.1
PyGithub==1.55
Pygments==2.12.0
PyJWT==2.4.0
pylev==1.4.0
pyluach==2.0.0
PyMeeus==0.5.11
PyNaCl==1.5.0
pyparsing==3.0.9
pyrsistent==0.18.1
pyspark==3.3.0
pystan==2.19.1.1
pytest==7.1.2
python-dateutil==2.8.2
pytz==2022.1
pytz-deprecation-shim==0.1.0.post0
pywin32==304
pywin32-ctypes==0.2.0
pywinpty==2.0.6
PyYAML==6.0
pyzmq==23.2.0
requests==2.28.1
requests-oauthlib==1.3.1
requests-toolbelt==0.9.1
retrying==1.3.3
rfc3987==1.3.8
rich==12.5.1
rpy2==3.5.3
rsa==4.9
s3transfer==0.6.0
scikit-learn==1.1.1
scipy==1.8.1
seaborn==0.11.2
Send2Trash==1.8.0
setuptools-git==1.2
shellingham==1.4.0
simplejson==3.17.6
six==1.15.0
sklearn==0.0
smart-open==5.2.1
smmap==5.0.0
sniffio==1.2.0
sortedcontainers==2.4.0
soupsieve==2.3.2.post1
spacy==3.4.1
spacy-legacy==3.0.9
spacy-loggers==1.0.3
srsly==2.4.4
stack-data==0.3.0
statistics==1.0.3.5
statsmodels==0.13.1
strict-rfc3339==0.7
swagger-spec-validator==2.7.4
tblib==1.7.0
tenacity==8.0.1
tensorboard==2.8.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorflow==2.8.0
tensorflow-estimator==2.9.0
tensorflow-gpu==2.6.0
tensorflow-io-gcs-filesystem==0.26.0
termcolor==1.1.0
terminado==0.15.0
tf-estimator-nightly==2.8.0.dev2021122109
thinc==8.1.0
threadpoolctl==3.1.0
tinycss2==1.1.1
tomli==2.0.1
tomlkit==0.11.1
toolz==0.11.2
torch==1.12.1
torchfitter==4.2.0
torchmetrics==0.9.3
tornado==6.2
tqdm==4.64.0
traitlets==5.3.0
typeguard==2.13.3
typer==0.4.2
typing_extensions==4.3.0
tzdata==2022.1
tzlocal==4.2
ujson==5.4.0
urllib3==1.26.11
vevestaX==6.7.0
virtualenv==20.16.2
virtualenv-clone==0.5.7
wasabi==0.10.1
wcwidth==0.2.5
webcolors==1.12
webencodings==0.5.1
websocket-client==1.3.3
Werkzeug==2.2.1
widgetsnbextension==3.6.1
wrapt==1.12.1
xlrd==2.0.1
XlsxWriter==3.0.3
yarl==1.7.2
yfinance==0.1.74
zict==2.2.0
zipp==3.8.1
zope.interface==5.4.0

```

windows 10 x64

```
C:\Users\User>nvidia-smi
Sun Aug 14 12:10:18 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 512.15       Driver Version: 512.15       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro M2000M      WDDM* | 00000000:01:00.0  On |                  N/A |
| N/A   46C    P8    N/A /  N/A |   3980MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A       596      C   ...ython\Python39\python.exe    N/A      |
|    0   N/A  N/A      1244    C+G                                   N/A      |
|    0   N/A  N/A      2540    C+G   ...5n1h2txyewy\SearchApp.exe    N/A      |
|    0   N/A  N/A      5628      C   ...ython\Python39\python.exe    N/A      |
|    0   N/A  N/A     17432    C+G   ...me\Application\chrome.exe    N/A      |
+-----------------------------------------------------------------------------+
```

![image](https://user-images.githubusercontent.com/5154106/184551394-33ec602b-5a59-4b6e-b91a-f1e9699b7031.png)
I read the driver version shown by nvidia-smi can be diff
https://stackoverflow.com/questions/53422407/different-cuda-versions-shown-by-nvcc-and-nvidia-smi
![image](https://user-images.githubusercontent.com/5154106/184551414-d06a04d4-35cc-4839-832b-2ce8d3115683.png)


Code that works with my gpu
```
# multivariate multi-step stacked lstm example
from numpy import array
from numpy import hstack
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from numpy import array
from numpy import hstack
from keras.layers import *
from keras.models import *
from keras import backend as K
 
from sklearn.preprocessing import PowerTransformer
power = PowerTransformer(method='yeo-johnson')

def stable_sigmoid(x):

    sig = np.where(x < 0, np.exp(x)/(1 + np.exp(x)), 1/(1 + np.exp(-x)))
    return sig

def inverse_sigmoid(x):
    inv_sig = -np.log((1 / (x + 1e-8)) - 1)
    return inv_sig
    
# split a multivariate sequence into samples
def split_sequences(sequences, n_steps_in, n_steps_out):
	X, y = list(), list()
	for i in range(len(sequences)):
		# find the end of this pattern
		end_ix = i + n_steps_in
		out_end_ix = end_ix + n_steps_out
		# check if we are beyond the dataset
		if out_end_ix > len(sequences):
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequences[i:end_ix, 0:2], sequences[end_ix-1:out_end_ix, 1][1:3]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)
     
# define input sequence
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90])
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95])
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])
# convert to [rows, columns] structure
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))
out_seq = out_seq.reshape((len(out_seq), 1))
# horizontally stack columns
dataset = hstack((in_seq1, in_seq2, out_seq))
# choose a number of time steps
n_steps_in, n_steps_out = 3, 2
# covert into input/output
X, y = split_sequences(dataset, n_steps_in, n_steps_out)



print(X.shape, y.shape)
# summarize the data
for i in range(len(X)):
	print(X[i], y[i])


n_features = X.shape[2]
# define model
model = Sequential()

model.add(LSTM(100, activation='tanh', return_sequences=True, input_shape=(n_steps_in, n_features)))
model.add(LSTM(100, activation='tanh'))
model.add(Dense(n_steps_out))

"""
model.add(Bidirectional(LSTM(100, activation='tanh', return_sequences=True), input_shape=(n_steps_in, n_features)))
#model.add(Bidirectional(LSTM(100, activation='relu'), input_shape=(n_steps_in, n_features)))
model.add(attention(return_sequences=True)) # receive 3D and output 3D
model.add(Dropout(0.5))
model.add(Dense(n_steps_out))
"""
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(X, y, epochs=200, verbose=0)
# demonstrate prediction
x_input = array([[70, 75], [80, 85], [90, 95]])
x_input = x_input.reshape((1, n_steps_in, n_features))
yhat = model.predict(x_input, verbose=1)
print(yhat)

```

setting value to False in the second guess got it run on cpu

I'll work on this useful breadcrumb
```
import torch
print(torch.cuda.is_available())
```

I think the issue is I have cuda 11.2 (which I read I need for cudnn) and pytorch expects 11.3

https://stackoverflow.com/questions/55717751/torch-cuda-is-available-keeps-switching-to-false

**Comment by Xylambda** [comment] 2022-08-14 22:03
I see. The reason it is not working is because PyTorch is not detecting CUDA.

I assume you installed the CUDA binaries [like it is required](https://pytorch.org/get-started/locally/). This is needed because neither this library nor `torchfitter` ship the necessary binaries and you have to do it manually.

Another reason could be the one you mentioned. Some options you have:

* Upgrade your CUDA version to 11.3. This could be dangerous since you are also using TensorFlow and it may break your installation. You would have to check the compatibility of 11.3 with Google's library. I am by no means an expert in TensorFlow so I don't have more specific instructions on how to perform this.
* According to [this answer](https://discuss.pytorch.org/t/want-to-install-pytorch-for-custom-cuda-version-cuda-11-2/141159) from the PyTorch forum, you could build PyTorch from source. This is the one I would try since the [required steps](https://github.com/pytorch/pytorch#from-source) seem pretty easy to follow.
* Try to make it work with the current CUDA version. [This issue](https://github.com/pytorch/pytorch/issues/50032) contains more info. and apparently PyTorch [supports CUDA 11.2](https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel_21-02.html#rel_21-02). Maybe try to reinstall following the steps from the official doc and check if it works.

Since the issue is not related to this library I am going to close it. Feel free to reopen it if you think I may help you with something.

**Closed as completed by Xylambda** 2022-08-14 22:03 UTC
